ktor:
  application:
    modules:
      - ru.serj.birds.ApplicationKt.moduleBird
  deployment:
    port: "$PORT:8080"
jwt:
  keycloak: $KEYCLOAK_BASE_URL
  issuer: "/auth/realms/otus-marketplace"
  audience: "ad-users"
  realm: "otus-marketplace"
  certPath: "/auth/realms/otus-marketplace/protocol/openid-connect/certs"
logging:
  provider: "logback"
dbms:
  vendor: postgres
  user: "$DB_USER:bob"
  password: "$DB_PASS:123"
  database: tweets
  driver: org.postgresql.Driver
  dbhost: "$DB_HOST:localhost"
  dbport: "$DB_PORT:5432"
  url: "jdbc:postgresql://"
