name: 'CI-build'

on:
  push:
    branches:
      - 'master'
      - 'develop'
      - 'task-*'
    pull_request:
      types:
        - opened
        - reopened
        - synchronize
      branches:
        - 'master'
        - 'develop'
        - 'task-*'
    workflow-dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Apt update
        run: sudo apt-get update
      - name: Install curl-dev
        run: sudo apt install -y libcurl4-openssl-dev
      - name: Run Tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

