name: 'CI-test'
on:
  push:
    branches-ignore:
      - 'v-*'
      - 'main'
      - 'master'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Apt update
        run: sudo apt-get update
      - name: Install curl-dev
        run: sudo apt install -y libcurl4-openssl-dev
      - name: Set gradlew executable
        run: chmod +x ./gradlew
      - name: Delete all previous versions of birds-app-api-base-v1
        uses: actions/delete-package-versions@v4
        with:
          package-name: 'ru.serj.birds-app-api-base-v1'
          package-type: 'maven'
          min-versions-to-keep: 1
          ignore-versions: '^(0|[1-9]\\d*)\\.0\\.0$'
          delete-only-pre-release-versions: "true"
      - name: Publish package
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Test package
        uses: gradle/gradle-build-action@v2
        with:
          arguments: check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
