name: 'CI-test'
on:
  push:
    branches-ignore:
      - 'v-*'
      - 'main'
      - 'master'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Install curl-dev
        run: sudo apt install -y libcurl4-openssl-dev
      - name: Test package
        run: gradle check
